'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { IcareAvatar as IcareAvatarElement, defineCustomElement as defineIcareAvatar } from "icare-components/dist/components/icare-avatar.js";
import { IcareBanner as IcareBannerElement, defineCustomElement as defineIcareBanner } from "icare-components/dist/components/icare-banner.js";
import { IcareButton as IcareButtonElement, defineCustomElement as defineIcareButton } from "icare-components/dist/components/icare-button.js";
import { IcareCard as IcareCardElement, defineCustomElement as defineIcareCard } from "icare-components/dist/components/icare-card.js";
import { IcareCaregiverMiniProfileCard as IcareCaregiverMiniProfileCardElement, defineCustomElement as defineIcareCaregiverMiniProfileCard } from "icare-components/dist/components/icare-caregiver-mini-profile-card.js";
import { IcareCaregiverProfileCard as IcareCaregiverProfileCardElement, defineCustomElement as defineIcareCaregiverProfileCard } from "icare-components/dist/components/icare-caregiver-profile-card.js";
import { IcareFooter as IcareFooterElement, defineCustomElement as defineIcareFooter } from "icare-components/dist/components/icare-footer.js";
import { IcareHeader as IcareHeaderElement, defineCustomElement as defineIcareHeader } from "icare-components/dist/components/icare-header.js";
import { IcareHeroNew as IcareHeroNewElement, defineCustomElement as defineIcareHeroNew } from "icare-components/dist/components/icare-hero-new.js";
import { IcareHero as IcareHeroElement, defineCustomElement as defineIcareHero } from "icare-components/dist/components/icare-hero.js";
import { IcareLogo as IcareLogoElement, defineCustomElement as defineIcareLogo } from "icare-components/dist/components/icare-logo.js";
import { IcareMessagesCard as IcareMessagesCardElement, defineCustomElement as defineIcareMessagesCard } from "icare-components/dist/components/icare-messages-card.js";
import { IcarePage as IcarePageElement, defineCustomElement as defineIcarePage } from "icare-components/dist/components/icare-page.js";
import { IcareRecommendedCaregiversCard as IcareRecommendedCaregiversCardElement, defineCustomElement as defineIcareRecommendedCaregiversCard } from "icare-components/dist/components/icare-recommended-caregivers-card.js";
import { IcareSection as IcareSectionElement, defineCustomElement as defineIcareSection } from "icare-components/dist/components/icare-section.js";
import { IcareShimmer as IcareShimmerElement, defineCustomElement as defineIcareShimmer } from "icare-components/dist/components/icare-shimmer.js";
import { IcareTextBlock as IcareTextBlockElement, defineCustomElement as defineIcareTextBlock } from "icare-components/dist/components/icare-text-block.js";
import { IcareWebBlock as IcareWebBlockElement, defineCustomElement as defineIcareWebBlock } from "icare-components/dist/components/icare-web-block.js";
import { IcareWebMinihero as IcareWebMiniheroElement, defineCustomElement as defineIcareWebMinihero } from "icare-components/dist/components/icare-web-minihero.js";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "icare-components/dist/components/my-component.js";
import React from 'react';

export type IcareAvatarEvents = NonNullable<unknown>;

export const IcareAvatar: StencilReactComponent<IcareAvatarElement, IcareAvatarEvents> = /*@__PURE__*/ createComponent<IcareAvatarElement, IcareAvatarEvents>({
    tagName: 'icare-avatar',
    elementClass: IcareAvatarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareAvatarEvents,
    defineCustomElement: defineIcareAvatar
});

export type IcareBannerEvents = NonNullable<unknown>;

export const IcareBanner: StencilReactComponent<IcareBannerElement, IcareBannerEvents> = /*@__PURE__*/ createComponent<IcareBannerElement, IcareBannerEvents>({
    tagName: 'icare-banner',
    elementClass: IcareBannerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareBannerEvents,
    defineCustomElement: defineIcareBanner
});

export type IcareButtonEvents = { onButtonClick: EventName<CustomEvent<void>> };

export const IcareButton: StencilReactComponent<IcareButtonElement, IcareButtonEvents> = /*@__PURE__*/ createComponent<IcareButtonElement, IcareButtonEvents>({
    tagName: 'icare-button',
    elementClass: IcareButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onButtonClick: 'buttonClick' } as IcareButtonEvents,
    defineCustomElement: defineIcareButton
});

export type IcareCardEvents = NonNullable<unknown>;

export const IcareCard: StencilReactComponent<IcareCardElement, IcareCardEvents> = /*@__PURE__*/ createComponent<IcareCardElement, IcareCardEvents>({
    tagName: 'icare-card',
    elementClass: IcareCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareCardEvents,
    defineCustomElement: defineIcareCard
});

export type IcareCaregiverMiniProfileCardEvents = NonNullable<unknown>;

export const IcareCaregiverMiniProfileCard: StencilReactComponent<IcareCaregiverMiniProfileCardElement, IcareCaregiverMiniProfileCardEvents> = /*@__PURE__*/ createComponent<IcareCaregiverMiniProfileCardElement, IcareCaregiverMiniProfileCardEvents>({
    tagName: 'icare-caregiver-mini-profile-card',
    elementClass: IcareCaregiverMiniProfileCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareCaregiverMiniProfileCardEvents,
    defineCustomElement: defineIcareCaregiverMiniProfileCard
});

export type IcareCaregiverProfileCardEvents = NonNullable<unknown>;

export const IcareCaregiverProfileCard: StencilReactComponent<IcareCaregiverProfileCardElement, IcareCaregiverProfileCardEvents> = /*@__PURE__*/ createComponent<IcareCaregiverProfileCardElement, IcareCaregiverProfileCardEvents>({
    tagName: 'icare-caregiver-profile-card',
    elementClass: IcareCaregiverProfileCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareCaregiverProfileCardEvents,
    defineCustomElement: defineIcareCaregiverProfileCard
});

export type IcareFooterEvents = NonNullable<unknown>;

export const IcareFooter: StencilReactComponent<IcareFooterElement, IcareFooterEvents> = /*@__PURE__*/ createComponent<IcareFooterElement, IcareFooterEvents>({
    tagName: 'icare-footer',
    elementClass: IcareFooterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareFooterEvents,
    defineCustomElement: defineIcareFooter
});

export type IcareHeaderEvents = NonNullable<unknown>;

export const IcareHeader: StencilReactComponent<IcareHeaderElement, IcareHeaderEvents> = /*@__PURE__*/ createComponent<IcareHeaderElement, IcareHeaderEvents>({
    tagName: 'icare-header',
    elementClass: IcareHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareHeaderEvents,
    defineCustomElement: defineIcareHeader
});

export type IcareHeroEvents = NonNullable<unknown>;

export const IcareHero: StencilReactComponent<IcareHeroElement, IcareHeroEvents> = /*@__PURE__*/ createComponent<IcareHeroElement, IcareHeroEvents>({
    tagName: 'icare-hero',
    elementClass: IcareHeroElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareHeroEvents,
    defineCustomElement: defineIcareHero
});

export type IcareHeroNewEvents = NonNullable<unknown>;

export const IcareHeroNew: StencilReactComponent<IcareHeroNewElement, IcareHeroNewEvents> = /*@__PURE__*/ createComponent<IcareHeroNewElement, IcareHeroNewEvents>({
    tagName: 'icare-hero-new',
    elementClass: IcareHeroNewElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareHeroNewEvents,
    defineCustomElement: defineIcareHeroNew
});

export type IcareLogoEvents = NonNullable<unknown>;

export const IcareLogo: StencilReactComponent<IcareLogoElement, IcareLogoEvents> = /*@__PURE__*/ createComponent<IcareLogoElement, IcareLogoEvents>({
    tagName: 'icare-logo',
    elementClass: IcareLogoElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareLogoEvents,
    defineCustomElement: defineIcareLogo
});

export type IcareMessagesCardEvents = { onNavigate: EventName<CustomEvent<string>> };

export const IcareMessagesCard: StencilReactComponent<IcareMessagesCardElement, IcareMessagesCardEvents> = /*@__PURE__*/ createComponent<IcareMessagesCardElement, IcareMessagesCardEvents>({
    tagName: 'icare-messages-card',
    elementClass: IcareMessagesCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onNavigate: 'navigate' } as IcareMessagesCardEvents,
    defineCustomElement: defineIcareMessagesCard
});

export type IcarePageEvents = NonNullable<unknown>;

export const IcarePage: StencilReactComponent<IcarePageElement, IcarePageEvents> = /*@__PURE__*/ createComponent<IcarePageElement, IcarePageEvents>({
    tagName: 'icare-page',
    elementClass: IcarePageElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcarePageEvents,
    defineCustomElement: defineIcarePage
});

export type IcareRecommendedCaregiversCardEvents = NonNullable<unknown>;

export const IcareRecommendedCaregiversCard: StencilReactComponent<IcareRecommendedCaregiversCardElement, IcareRecommendedCaregiversCardEvents> = /*@__PURE__*/ createComponent<IcareRecommendedCaregiversCardElement, IcareRecommendedCaregiversCardEvents>({
    tagName: 'icare-recommended-caregivers-card',
    elementClass: IcareRecommendedCaregiversCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareRecommendedCaregiversCardEvents,
    defineCustomElement: defineIcareRecommendedCaregiversCard
});

export type IcareSectionEvents = NonNullable<unknown>;

export const IcareSection: StencilReactComponent<IcareSectionElement, IcareSectionEvents> = /*@__PURE__*/ createComponent<IcareSectionElement, IcareSectionEvents>({
    tagName: 'icare-section',
    elementClass: IcareSectionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareSectionEvents,
    defineCustomElement: defineIcareSection
});

export type IcareShimmerEvents = NonNullable<unknown>;

export const IcareShimmer: StencilReactComponent<IcareShimmerElement, IcareShimmerEvents> = /*@__PURE__*/ createComponent<IcareShimmerElement, IcareShimmerEvents>({
    tagName: 'icare-shimmer',
    elementClass: IcareShimmerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareShimmerEvents,
    defineCustomElement: defineIcareShimmer
});

export type IcareTextBlockEvents = NonNullable<unknown>;

export const IcareTextBlock: StencilReactComponent<IcareTextBlockElement, IcareTextBlockEvents> = /*@__PURE__*/ createComponent<IcareTextBlockElement, IcareTextBlockEvents>({
    tagName: 'icare-text-block',
    elementClass: IcareTextBlockElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareTextBlockEvents,
    defineCustomElement: defineIcareTextBlock
});

export type IcareWebBlockEvents = NonNullable<unknown>;

export const IcareWebBlock: StencilReactComponent<IcareWebBlockElement, IcareWebBlockEvents> = /*@__PURE__*/ createComponent<IcareWebBlockElement, IcareWebBlockEvents>({
    tagName: 'icare-web-block',
    elementClass: IcareWebBlockElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareWebBlockEvents,
    defineCustomElement: defineIcareWebBlock
});

export type IcareWebMiniheroEvents = NonNullable<unknown>;

export const IcareWebMinihero: StencilReactComponent<IcareWebMiniheroElement, IcareWebMiniheroEvents> = /*@__PURE__*/ createComponent<IcareWebMiniheroElement, IcareWebMiniheroEvents>({
    tagName: 'icare-web-minihero',
    elementClass: IcareWebMiniheroElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcareWebMiniheroEvents,
    defineCustomElement: defineIcareWebMinihero
});

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});
