<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ICare.Infrastructure\ICare.Infrastructure.csproj" />
    <ProjectReference Include="..\ICare.Application\ICare.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.41" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\Requests\" />
  </ItemGroup>

</Project>
