ALTER TABLE carereceiver_dashboard_bookings
  ADD COLUMN IF NOT EXISTS booking_ref VARCHAR(32),
  ADD COLUMN IF NOT EXISTS caregiver_id VARCHAR(64),
  ADD COLUMN IF NOT EXISTS caregiver_phone VARCHAR(40),
  ADD COLUMN IF NOT EXISTS caregiver_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS caregiver_rating NUMERIC(3, 2),
  ADD COLUMN IF NOT EXISTS caregiver_review_count INTEGER,
  ADD COLUMN IF NOT EXISTS caregiver_verification_badges TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS service_type TEXT,
  ADD COLUMN IF NOT EXISTS service_types TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS special_requests TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS duration_hours NUMERIC(5, 2),
  ADD COLUMN IF NOT EXISTS payment_hourly_rate NUMERIC(8, 2),
  ADD COLUMN IF NOT EXISTS payment_duration NUMERIC(5, 2),
  ADD COLUMN IF NOT EXISTS payment_subtotal NUMERIC(8, 2),
  ADD COLUMN IF NOT EXISTS payment_service_fee NUMERIC(8, 2),
  ADD COLUMN IF NOT EXISTS payment_service_fee_percentage NUMERIC(5, 2),
  ADD COLUMN IF NOT EXISTS payment_total NUMERIC(8, 2),
  ADD COLUMN IF NOT EXISTS payment_method TEXT,
  ADD COLUMN IF NOT EXISTS payment_refund_amount NUMERIC(8, 2),
  ADD COLUMN IF NOT EXISTS emergency_contact_name TEXT,
  ADD COLUMN IF NOT EXISTS emergency_contact_phone TEXT,
  ADD COLUMN IF NOT EXISTS emergency_contact_relationship TEXT,
  ADD COLUMN IF NOT EXISTS requested_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS confirmation_deadline TIMESTAMP,
  ADD COLUMN IF NOT EXISTS decline_reason TEXT,
  ADD COLUMN IF NOT EXISTS cancelled_date DATE,
  ADD COLUMN IF NOT EXISTS timeline_json JSONB;

INSERT INTO carereceiver_dashboard_bookings (
  id,
  care_receiver_id,
  caregiver_id,
  caregiver_name,
  caregiver_photo_url,
  caregiver_phone,
  caregiver_email,
  caregiver_rating,
  caregiver_review_count,
  caregiver_verification_badges,
  booking_ref,
  booking_date,
  start_time,
  duration_hours,
  status,
  response_deadline,
  confirmation_deadline,
  conversation_id,
  service_type,
  service_types,
  special_requests,
  address,
  payment_hourly_rate,
  payment_duration,
  payment_subtotal,
  payment_service_fee,
  payment_service_fee_percentage,
  payment_total,
  payment_method,
  payment_refund_amount,
  emergency_contact_name,
  emergency_contact_phone,
  emergency_contact_relationship,
  requested_at,
  accepted_at,
  completed_at,
  has_review,
  created_at,
  updated_at
)
VALUES
  (
    'bk-2026-1101', NULL, 'cg-emma-wilson', 'Emma Wilson', '/images/avatars/female.webp',
    '07700 900321', 'emma.wilson@example.com', 4.7, 18, ARRAY['Identity Verified','DBS Verified']::text[],
    'BK-2026-1101', CURRENT_DATE + INTERVAL '1 day', TIME '14:00', 3.00, 'requested',
    NOW() + INTERVAL '20 hours', NULL, 'conv-2101', 'Companionship', ARRAY['Companionship','Light housework']::text[],
    'Please include a short walk and tea break.', '42 Rosemary Lane, Islington, London N1 2AB',
    18.00, 3.00, 54.00, 2.70, 5.00, 56.70, 'Visa ending in 4242', 56.70,
    'David Harrison', '07700 900456', 'Son', NOW() - INTERVAL '30 minutes', NULL, NULL, FALSE, NOW(), NOW()
  ),
  (
    'bk-2026-1102', NULL, 'cg-john-anderson', 'John Anderson', '/images/avatars/male.webp',
    '07700 900654', 'john.anderson@example.com', 4.6, 21, ARRAY['Identity Verified']::text[],
    'BK-2026-1102', CURRENT_DATE + INTERVAL '2 days', TIME '10:00', 4.00, 'requested',
    NOW() + INTERVAL '5 hours', NULL, 'conv-2102', 'Shopping and errands', ARRAY['Shopping and errands']::text[],
    'Need support with grocery shopping.', '42 Rosemary Lane, Islington, London N1 2AB',
    19.00, 4.00, 76.00, 3.80, 5.00, 79.80, 'Mastercard ending in 1337', 79.80,
    'David Harrison', '07700 900456', 'Son', NOW() - INTERVAL '2 hours', NULL, NULL, FALSE, NOW(), NOW()
  ),
  (
    'bk-2026-1103', NULL, 'cg-margaret-thompson', 'Margaret Thompson', '/images/avatars/female.webp',
    '07700 900741', 'margaret.thompson@example.com', 4.9, 31, ARRAY['Identity Verified','DBS Verified','Right to Work Verified']::text[],
    'BK-2026-1103', CURRENT_DATE + INTERVAL '3 days', TIME '09:00', 3.00, 'requested',
    NOW() + INTERVAL '12 hours', NULL, 'conv-2103', 'Meal preparation', ARRAY['Meal preparation']::text[],
    'Prefers low-salt meals.', '42 Rosemary Lane, Islington, London N1 2AB',
    20.00, 3.00, 60.00, 3.00, 5.00, 63.00, 'Visa ending in 4242', 63.00,
    'David Harrison', '07700 900456', 'Son', NOW() - INTERVAL '1 hour', NULL, NULL, FALSE, NOW(), NOW()
  ),
  (
    'bk-2026-1201', NULL, 'cg-mary-thompson', 'Mary Thompson', '/images/avatars/female.webp',
    '07700 901111', 'mary.thompson@example.com', 4.8, 24, ARRAY['Identity Verified','DBS Verified']::text[],
    'BK-2026-1201', CURRENT_DATE + INTERVAL '2 days', TIME '10:00', 4.00, 'accepted',
    NULL, NOW() + INTERVAL '48 hours', 'conv-1002', 'Companionship', ARRAY['Companionship']::text[],
    'Light walk in the nearby park if weather allows.', '42 Rosemary Lane, Islington, London N1 2AB',
    18.00, 4.00, 72.00, 3.60, 5.00, 75.60, 'Visa ending in 4242', 75.60,
    'David Harrison', '07700 900456', 'Son', NOW() - INTERVAL '24 hours', NOW() - INTERVAL '20 hours', NULL, FALSE, NOW(), NOW()
  ),
  (
    'bk-2026-1202', NULL, 'cg-emma-wilson', 'Emma Wilson', '/images/avatars/female.webp',
    '07700 900321', 'emma.wilson@example.com', 4.7, 18, ARRAY['Identity Verified','DBS Verified']::text[],
    'BK-2026-1202', CURRENT_DATE + INTERVAL '4 days', TIME '14:00', 3.00, 'accepted',
    NULL, NOW() + INTERVAL '72 hours', 'conv-1012', 'Light housework', ARRAY['Light housework','Companionship']::text[],
    'Vacuum living room and fold laundry.', '42 Rosemary Lane, Islington, London N1 2AB',
    18.00, 3.00, 54.00, 2.70, 5.00, 56.70, 'Visa ending in 4242', 56.70,
    'David Harrison', '07700 900456', 'Son', NOW() - INTERVAL '36 hours', NOW() - INTERVAL '32 hours', NULL, FALSE, NOW(), NOW()
  ),
  (
    'bk-2026-1203', NULL, 'cg-john-anderson', 'John Anderson', '/images/avatars/male.webp',
    '07700 900654', 'john.anderson@example.com', 4.6, 21, ARRAY['Identity Verified']::text[],
    'BK-2026-1203', CURRENT_DATE, TIME '14:00', 3.00, 'in_progress',
    NULL, NULL, 'conv-1011', 'Companionship', ARRAY['Companionship']::text[],
    'Tea and board games this afternoon.', '42 Rosemary Lane, Islington, London N1 2AB',
    19.00, 3.00, 57.00, 2.85, 5.00, 59.85, 'Mastercard ending in 1337', 59.85,
    'David Harrison', '07700 900456', 'Son', NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', NULL, FALSE, NOW(), NOW()
  ),
  (
    'bk-2026-0151', NULL, 'cg-mary-thompson', 'Mary Thompson', '/images/avatars/female.webp',
    '07700 901111', 'mary.thompson@example.com', 4.8, 24, ARRAY['Identity Verified','DBS Verified']::text[],
    'BK-2026-0151', CURRENT_DATE - INTERVAL '2 days', TIME '14:00', 3.00, 'completed',
    NULL, NULL, 'conv-1002', 'Companionship', ARRAY['Companionship']::text[],
    'Gentle walk and light conversation.', '42 Rosemary Lane, Islington, London N1 2AB',
    18.00, 3.00, 54.00, 2.70, 5.00, 56.70, 'Visa ending in 4242', 56.70,
    'David Harrison', '07700 900456', 'Son', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days 2 hours', NOW() - INTERVAL '2 hours', FALSE, NOW(), NOW()
  ),
  (
    'bk-2026-0128', NULL, 'cg-emma-wilson', 'Emma Wilson', '/images/avatars/female.webp',
    '07700 900321', 'emma.wilson@example.com', 4.7, 18, ARRAY['Identity Verified','DBS Verified']::text[],
    'BK-2026-0128', CURRENT_DATE - INTERVAL '3 days', TIME '10:00', 4.00, 'payment_released',
    NULL, NULL, 'conv-1012', 'Light housework', ARRAY['Light housework']::text[],
    'Kitchen tidy-up and meal prep.', '42 Rosemary Lane, Islington, London N1 2AB',
    18.00, 4.00, 72.00, 3.60, 5.00, 75.60, 'Visa ending in 4242', 75.60,
    'David Harrison', '07700 900456', 'Son', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days 1 hour', NOW() - INTERVAL '26 hours', FALSE, NOW(), NOW()
  )
ON CONFLICT (id) DO UPDATE SET
  caregiver_id = EXCLUDED.caregiver_id,
  caregiver_name = EXCLUDED.caregiver_name,
  caregiver_photo_url = EXCLUDED.caregiver_photo_url,
  caregiver_phone = EXCLUDED.caregiver_phone,
  caregiver_email = EXCLUDED.caregiver_email,
  caregiver_rating = EXCLUDED.caregiver_rating,
  caregiver_review_count = EXCLUDED.caregiver_review_count,
  caregiver_verification_badges = EXCLUDED.caregiver_verification_badges,
  booking_ref = EXCLUDED.booking_ref,
  booking_date = EXCLUDED.booking_date,
  start_time = EXCLUDED.start_time,
  duration_hours = EXCLUDED.duration_hours,
  status = EXCLUDED.status,
  response_deadline = EXCLUDED.response_deadline,
  confirmation_deadline = EXCLUDED.confirmation_deadline,
  conversation_id = EXCLUDED.conversation_id,
  service_type = EXCLUDED.service_type,
  service_types = EXCLUDED.service_types,
  special_requests = EXCLUDED.special_requests,
  address = EXCLUDED.address,
  payment_hourly_rate = EXCLUDED.payment_hourly_rate,
  payment_duration = EXCLUDED.payment_duration,
  payment_subtotal = EXCLUDED.payment_subtotal,
  payment_service_fee = EXCLUDED.payment_service_fee,
  payment_service_fee_percentage = EXCLUDED.payment_service_fee_percentage,
  payment_total = EXCLUDED.payment_total,
  payment_method = EXCLUDED.payment_method,
  payment_refund_amount = EXCLUDED.payment_refund_amount,
  emergency_contact_name = EXCLUDED.emergency_contact_name,
  emergency_contact_phone = EXCLUDED.emergency_contact_phone,
  emergency_contact_relationship = EXCLUDED.emergency_contact_relationship,
  requested_at = EXCLUDED.requested_at,
  accepted_at = EXCLUDED.accepted_at,
  completed_at = EXCLUDED.completed_at,
  has_review = EXCLUDED.has_review,
  updated_at = NOW();
