INSERT INTO users (
  email,
  email_verified,
  email_verified_at,
  password_hash,
  phone,
  phone_verified,
  phone_verified_at,
  phone_country_code,
  user_type,
  first_name,
  last_name,
  date_of_birth,
  account_status,
  gdpr_consent,
  gdpr_consent_date,
  marketing_consent,
  created_at,
  updated_at,
  deleted_at
)
VALUES (
  'maxherbst1985@gmail.com',
  FALSE,
  NULL,
  '$2a$10$hAcKG41LPn.IEG0isaCw/.4xkwbhO6mBFkWVRnEHLkOjXXjWwzXZW',
  '+48500123456',
  FALSE,
  NULL,
  '+48',
  'caregiver',
  'Margaret',
  'Shaw',
  DATE '1988-04-12',
  'active',
  TRUE,
  NOW(),
  FALSE,
  NOW(),
  NOW(),
  NULL
)
ON CONFLICT (email) DO UPDATE
SET
  password_hash = EXCLUDED.password_hash,
  phone = EXCLUDED.phone,
  phone_verified = EXCLUDED.phone_verified,
  phone_verified_at = EXCLUDED.phone_verified_at,
  phone_country_code = EXCLUDED.phone_country_code,
  user_type = EXCLUDED.user_type,
  first_name = EXCLUDED.first_name,
  last_name = EXCLUDED.last_name,
  date_of_birth = EXCLUDED.date_of_birth,
  account_status = EXCLUDED.account_status,
  gdpr_consent = EXCLUDED.gdpr_consent,
  gdpr_consent_date = EXCLUDED.gdpr_consent_date,
  marketing_consent = EXCLUDED.marketing_consent,
  updated_at = NOW(),
  deleted_at = NULL;
