<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ICare.Application\ICare.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Stripe.net" Version="50.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ExternalServices\BackgroundJobs\" />
    <Folder Include="ExternalServices\Communication\" />
    <Folder Include="ExternalServices\Geocodings\" />
    <Folder Include="ExternalServices\Identity\" />
    <Folder Include="ExternalServices\Stripe\" />
    <Folder Include="Persistence\Configurations\" />
    <Folder Include="Persistence\Interceptors\" />
    <Folder Include="Persistence\Migrations\" />
    <Folder Include="Persistence\Repositories\" />
  </ItemGroup>

</Project>
